#!/usr/bin/env bash
set -e

# Determine if an gum is in the PATH
if ! type -p gum >/dev/null; then
  echo "gum not found on the system" >&2
  exit 1
fi

commitTypes="fix\nfeat\ndocs\nstyle\nrefactor\ntest\nchore\nrevert"

scopeFile=$(pwd)/.scopes

# verbose=""
# name_arg=""
# while [ $# -gt 0 ]; do
#   case "$1" in
#   --verbose)
#     verbose=1
#     ;;
#   --name)
#     name_arg="$2"
#     shift
#     ;;
#   -h|--help)
#     echo "Add help text here."
#     exit 0
#     ;;
#   esac
#   shift
# done

echo "Pick Commit Type"
TYPE=$(echo -e $commitTypes | gum filter --no-strict )

if test -f "$scopeFile"; then
    echo "Pick Commit Scopes"
    SCOPE=$(echo $scopeFile | gum filter --no-stric --no-lint )
else
    echo "Enter Commit Scopes"
    SCOPE=$(gum input --placeholder "scope")
fi
test -n "$SCOPE" && SCOPE="($SCOPE)"

echo "Enter Commit Summary"
SUMMARY=$(gum input --value "$TYPE$SCOPE: " --char-limit=50 --placeholder "Summary of this change")
echo "Enter Commit Details"
DESCRIPTION=$(gum write --placeholder "Details of this change (CTRL+D to finish)")

git commit -m "$SUMMARY" -m "$DESCRIPTION" -e