#!/usr/bin/env bash
set -e

# Determine if an gum is in the PATH
if ! type -p gum >/dev/null; then
  echo "gum not found on the system" >&2
  exit 1
fi

commitTypes="fix\nfeat\ndocs\nstyle\nrefactor\ntest\nchore\nrevert"

scopeFile=$(pwd)/.scopes

# verbose=""
# name_arg=""
# while [ $# -gt 0 ]; do
#   case "$1" in
#   --verbose)
#     verbose=1
#     ;;
#   --name)
#     name_arg="$2"
#     shift
#     ;;
#   -h|--help)
#     echo "Add help text here."
#     exit 0
#     ;;
#   esac
#   shift
# done

TYPE=$(echo -e $commitTypes | gum filter --no-strict --prompt="Pick Commit Type: " )

if test -f "$scopeFile"; then
    SCOPE=$(cat $scopeFile | gum filter --no-strict --prompt="Pick Commit Scope: " )
else
    SCOPE=$(gum input --placeholder "scope" --header="Pick Commit Scope: ")
fi

test -n "$SCOPE" && SCOPE="($SCOPE)"


SUMMARY=$(gum input --header="Enter Commit Summary: " --value "$TYPE$SCOPE: " --width 50 --char-limit=50 --placeholder "Summary of this change")
DESCRIPTION=$(gum write --header="Enter Commit Details: "  --width 80 --placeholder "Details of this change (CTRL+D to finish)")


git commit -m "$SUMMARY" -m "$DESCRIPTION" -e